## See https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/README.md
##
## export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 when running conformance binary

receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
  resourcedetection:
    detectors: [gcp]
    timeout: 10s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]

