services:

  tessera-conformance-posix:
    container_name: tessera-conformance-posix
    build:
      context: ../../../../
      dockerfile: ./cmd/conformance/posix/docker/Dockerfile
    ports:
      - "2025:2025"
    environment:
      LOG_PRIVATE_KEY: "PRIVATE+KEY+example.com/log/testdata+33d7b496+AeymY/SZAX0jZcJ8enZ5FY1Dz+wTML2yWSkK+9DSF3eg"
      LOG_PUBLIC_KEY: "example.com/log/testdata+33d7b496+AeHTu4Q3hEIMHNqc6fASMsq3rKNx280NI+oO5xCFkkSx"
    command: [
      "--storage_dir=/tmp/tessera-posix-log",
      "--initialise",
      "--listen=:2025",
      "--alsologtostderr",
      "--v=2",
    ]
    volumes:
      - /tmp/tessera-posix-log:/tmp/tessera-posix-log
    restart: always
