name: 'Terragrunt format check'
on:
  - pull_request

# Declare default permissions as read only.
permissions: read-all

env:
  tf_version: '1.5.7'
  tg_version: '0.55.1'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@cf355638dbd066b6a70eb01f31ad9293870a0e34 # v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'deployment'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
