name: 'Terragrunt format check'
on:
  - pull_request

permissions:
  contents: read

env:
  tofu_version: '1.10.0'
  tg_version: '0.77.22'

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@9272fa2cc60eefcd9ff2f07b3f7b880e47e6850a # v3.0.1
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: 'deployment'
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
